INSERT INTO @ohdsiSchema.CONCEPT_SET_NEGATIVE_CONTROLS
           (evidence_job_id
					 ,source_id
           ,concept_set_id
           ,concept_set_name
           ,negative_control
           ,concept_id
           ,concept_name
           ,domain_id
           ,person_count_rc
           ,person_count_dc
           ,descendant_pmid_count
           ,exact_pmid_count
           ,parent_pmid_count
           ,ancestor_pmid_count
           ,indication
					 ,too_broad
           ,drug_induced
           ,pregnancy					
           ,splicer
           ,faers
           ,user_excluded
           ,user_included)
     VALUES
           (?
					 ,?
           ,?
					 ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
)
