SELECT *
INTO #NC_ADE_SUMMARY
FROM (

  /*PULL ALL PMIDS THAT ARE IN A DESCENDANT RELATIONSHIP TO THE OUTCOME OF INTEREST*/
	SELECT 'DESCENDANT' AS MAPPING_TYPE,
		u.CONCEPT_ID AS OUTCOME_OF_INTEREST_CONCEPT_ID,
		u.CONCEPT_NAME AS OUTCOME_OF_INTEREST_CONCEPT_NAME,
		a.UNIQUE_IDENTIFIER,
		a.UNIQUE_IDENTIFIER_TYPE,
		a.EVIDENCE_TYPE AS PUBLICATION_TYPE
	FROM #NC_CONCEPT_UNIVERSE  u
		JOIN @vocabulary.CONCEPT_ANCESTOR ca
			ON ca.ANCESTOR_CONCEPT_ID = u.CONCEPT_ID
		JOIN (SELECT CONCEPT_ID_1, CONCEPT_ID_2, UNIQUE_IDENTIFIER, UNIQUE_IDENTIFIER_TYPE, EVIDENCE_TYPE FROM @evidenceSchema.CEM_UNIFIED WHERE LOWER(source_id) = LOWER('medline_winnenburg')) a
			{@outcomeOfInterest == 'condition'}?{
			  ON a.CONCEPT_ID_2 = ca.DESCENDANT_CONCEPT_ID
			  AND a.CONCEPT_ID_2 != ca.ANCESTOR_CONCEPT_ID
			}
			{@outcomeOfInterest == 'drug'}?{
			  ON a.CONCEPT_ID_1 = ca.DESCENDANT_CONCEPT_ID
			  AND a.CONCEPT_ID_1 != ca.ANCESTOR_CONCEPT_ID
			}
	WHERE
	  {@outcomeOfInterest == 'condition'}?{CONCEPT_ID_1}
	  {@outcomeOfInterest == 'drug'}?{CONCEPT_ID_2}
	  IN (
		SELECT CONCEPT_ID
		FROM @vocabulary.CONCEPT
		WHERE CONCEPT_ID IN (@conceptsOfInterest)
		UNION ALL
		SELECT DESCENDANT_CONCEPT_ID
		FROM @vocabulary.CONCEPT_ANCESTOR
		WHERE ANCESTOR_CONCEPT_ID IN (@conceptsOfInterest)
	)

	UNION ALL

  /*PULL ALL PMIDS THAT ARE IN A EXACT RELATIONSHIP TO THE OUTCOME OF INTEREST*/
	SELECT 'EXACT' AS MAPPING_TYPE,
		u.CONCEPT_ID AS OUTCOME_OF_INTEREST_CONCEPT_ID,
		u.CONCEPT_NAME AS OUTCOME_OF_INTEREST_CONCEPT_NAME,
		a.UNIQUE_IDENTIFIER,
		a.UNIQUE_IDENTIFIER_TYPE,
		a.EVIDENCE_TYPE AS PUBLICATION_TYPE
	FROM #NC_CONCEPT_UNIVERSE  u
		JOIN (SELECT CONCEPT_ID_1, CONCEPT_ID_2, UNIQUE_IDENTIFIER, UNIQUE_IDENTIFIER_TYPE, EVIDENCE_TYPE FROM @evidenceSchema.CEM_UNIFIED WHERE LOWER(source_id) = LOWER('medline_winnenburg')) a
		  {@outcomeOfInterest == 'condition'}?{
			  ON a.CONCEPT_ID_2 = u.CONCEPT_ID
			}
			{@outcomeOfInterest == 'drug'}?{
			  ON a.CONCEPT_ID_1 = u.CONCEPT_ID
			}
	WHERE
	  {@outcomeOfInterest == 'condition'}?{CONCEPT_ID_1}
	  {@outcomeOfInterest == 'drug'}?{CONCEPT_ID_2}
	  IN (
		SELECT CONCEPT_ID
		FROM @vocabulary.CONCEPT
		WHERE CONCEPT_ID IN (@conceptsOfInterest)
		UNION ALL
		SELECT DESCENDANT_CONCEPT_ID
		FROM @vocabulary.CONCEPT_ANCESTOR
		WHERE ANCESTOR_CONCEPT_ID IN (@conceptsOfInterest)
	)

	UNION ALL

  /*PULL ALL PMIDS THAT ARE IN A PARENT RELATIONSHIP TO THE OUTCOME OF INTEREST*/
	SELECT 'PARENT' AS MAPPING_TYPE,
		u.CONCEPT_ID AS OUTCOME_OF_INTEREST_CONCEPT_ID,
		u.CONCEPT_NAME AS OUTCOME_OF_INTEREST_CONCEPT_NAME,
		a.UNIQUE_IDENTIFIER,
		a.UNIQUE_IDENTIFIER_TYPE,
		a.EVIDENCE_TYPE AS PUBLICATION_TYPE
	FROM #NC_CONCEPT_UNIVERSE  u
		JOIN @vocabulary.CONCEPT_RELATIONSHIP cr
  		  ON cr.CONCEPT_ID_1 = u.CONCEPT_ID
			  AND UPPER(cr.RELATIONSHIP_ID) = 'IS A'
		JOIN (SELECT CONCEPT_ID_1, CONCEPT_ID_2, UNIQUE_IDENTIFIER, UNIQUE_IDENTIFIER_TYPE, EVIDENCE_TYPE FROM @evidenceSchema.CEM_UNIFIED WHERE LOWER(source_id) = LOWER('medline_winnenburg')) a
			{@outcomeOfInterest == 'condition'}?{
  		  ON a.CONCEPT_ID_2 = cr.CONCEPT_ID_2
			  AND a.CONCEPT_ID_2 != cr.CONCEPT_ID_1
  		}
  		{@outcomeOfInterest == 'drug'}?{
  		  ON a.CONCEPT_ID_1 = cr.CONCEPT_ID_2
			  AND a.CONCEPT_ID_1 != cr.CONCEPT_ID_1
  		}
	WHERE
	  {@outcomeOfInterest == 'condition'}?{a.CONCEPT_ID_1}
	  {@outcomeOfInterest == 'drug'}?{a.CONCEPT_ID_2}
	  IN (
		SELECT CONCEPT_ID
		FROM @vocabulary.CONCEPT
		WHERE CONCEPT_ID IN (@conceptsOfInterest)
		UNION ALL
		SELECT DESCENDANT_CONCEPT_ID
		FROM @vocabulary.CONCEPT_ANCESTOR
		WHERE ANCESTOR_CONCEPT_ID IN (@conceptsOfInterest)
	)

	UNION ALL

  /*PULL ALL PMIDS THAT ARE IN A ANCESTOR RELATIONSHIP TO THE OUTCOME OF INTEREST*/
	SELECT 'ANCESTOR' AS MAPPING_TYPE,
		u.CONCEPT_ID AS OUTCOME_OF_INTEREST_CONCEPT_ID,
		u.CONCEPT_NAME AS OUTCOME_OF_INTEREST_CONCEPT_NAME,
		a.UNIQUE_IDENTIFIER,
		a.UNIQUE_IDENTIFIER_TYPE,
		a.EVIDENCE_TYPE AS PUBLICATION_TYPE
	FROM #NC_CONCEPT_UNIVERSE  u
		JOIN @vocabulary.CONCEPT_ANCESTOR ca
			ON ca.DESCENDANT_CONCEPT_ID = u.CONCEPT_ID
		JOIN (SELECT CONCEPT_ID_1, CONCEPT_ID_2, UNIQUE_IDENTIFIER, UNIQUE_IDENTIFIER_TYPE, EVIDENCE_TYPE FROM @evidenceSchema.CEM_UNIFIED WHERE LOWER(source_id) = LOWER('medline_winnenburg')) a
			{@outcomeOfInterest == 'condition'}?{
			  ON a.CONCEPT_ID_2 = ca.ANCESTOR_CONCEPT_ID
			  AND a.CONCEPT_ID_2 != ca.DESCENDANT_CONCEPT_ID
			}
			{@outcomeOfInterest == 'drug'}?{
			  ON a.CONCEPT_ID_1 = ca.ANCESTOR_CONCEPT_ID
		  	AND a.CONCEPT_ID_1 != ca.DESCENDANT_CONCEPT_ID
			}
	WHERE
	  {@outcomeOfInterest == 'condition'}?{CONCEPT_ID_1}
	  {@outcomeOfInterest == 'drug'}?{CONCEPT_ID_2}
	  IN (
		SELECT CONCEPT_ID
		FROM @vocabulary.CONCEPT
		WHERE CONCEPT_ID IN (@conceptsOfInterest)
		UNION ALL
		SELECT DESCENDANT_CONCEPT_ID
		FROM @vocabulary.CONCEPT_ANCESTOR
		WHERE ANCESTOR_CONCEPT_ID IN (@conceptsOfInterest)
	)

) z;

